services:
  intro:
    build: ./intro
    container_name: intro_cont
    ports:
      - "7070:8000"
    volumes:
      - ./intro:/app
    depends_on:
    - mysql 
  gamepicker:
    build: ./game_picker
    container_name: picker_cont
    ports:
      - "7072:8000"
    volumes:
      - ./game_picker:/app  
    depends_on:
      - mysql    
  savegame:
    build: ./savegame
    container_name: savegame_cont
    ports:
      - "7071:8000"
    volumes:
      - ./savegame:/app
    depends_on:
      - mysql
  memorygame:
    build: ./memory_game
    container_name: memorygame_cont
    ports:
      - "7073:8000"
    volumes:
      - ./memory_game:/app
  guessgame:
    build: ./guess_game
    container_name: guessgame_cont
    ports:
      - "7074:8000"
    volumes:
      - ./guess_game:/app    
    
  mysql:
    build: ./mysql
    container_name: mysql_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: games
      MYSQL_USER: wog_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
  

volumes:
  mysql_data: