version: '3.8'

services:
  intro:
    build: ./intro
    image: adiros/wog_final-intro:latest
    container_name: intro_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./intro:/app
    depends_on:
    - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py runserver 0.0.0.0:8000"  
    environment:
      - DJANGO_ALLOWED_HOSTS=intro.local

  game_picker:
    build: ./game_picker
    image: adiros/wog_final-game_picker:latest
    container_name: picker_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./game_picker:/app
    depends_on:
      - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=game-picker.local

  savegame:
    build: ./savegame
    image: adiros/wog_final-savegame:latest
    container_name: savegame_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./savegame:/app
    depends_on:
      - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=savegame.local

  memory_game:
    build: ./memory_game
    image: adiros/wog_final-memory_game:latest
    container_name: memorygame_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./memory_game:/app
    depends_on:
      - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=memory-game.local

  guess_game:
    build: ./guess_game
    image: adiros/wog_final-guess_game:latest
    container_name: guessgame_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./guess_game:/app
    depends_on:
      - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=guess-game.local

  currency_roulette:
    build: ./currency_roulette
    image: adiros/wog_final-currency_roulette:latest
    container_name: currency_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./currency_roulette:/app
    depends_on:
      - mysql
    command: >
     sh -c "until nc -z -v -w60 mysql 3306; do echo 'Waiting for MySQL...'; sleep 10; done &&
     python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=currency-roulette.local

  selenium_tests:
    build: ./selenium_tests
    container_name: selenium_cont
    image: adiros/wog_final-selenium_tests:latest
    volumes:
      - ./selenium_tests:/app
    depends_on:
      - intro
      - game_picker
      - savegame
      - memory_game
      - guess_game
      - currency_roulette
      - mysql
    environment:
      - WAIT_HOSTS=mysql:3306,intro:8000

  mysql:
    build: ./mysql
    image: adiros/wog_final-mysql:latest
    container_name: mysql_cont
    ports:
      - "3306:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: games
      MYSQL_USER: wog_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "wog_user", "-puserpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

