apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: wog-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: adiros/wog_final-mysql:latest
        ports:
        - containerPort: 3306  
        volumeMounts:
        - mountPath: /var/lib/mysql  
          name: mysql-storage
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "games"
        - name: MYSQL_USER
          value: "wog_user"
        - name: MYSQL_PASSWORD
          value: "userpassword"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: wog-namespace
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306  
    targetPort: 3306
  type: ClusterIP
